netscaler/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^', include('vips.urls', namespace='vips' )),
)

vips/urls.py
from django.contrib.auth.decorators import login_required

__author__ = 'jeffrey.dambly'

from django.conf.urls import patterns, url
from vips import views

urlpatterns = patterns('',
                       url(
                           regex=r'^$',
                           view=views.IndexView.as_view(),
                           name='index'
                       ),
                       url(
                           regex=r'^devices/$',
                           view=views.DeviceList.as_view(),
                           name='devices'
                       ),
                       url(
                           regex=r'^device/create/$',
                           view=views.CreateDevice.as_view(),
                           name='createdevice'
                       ),
                       url(
                           regex=r'device/(?P<pk>\d+)>/delete',
                           view=views.DeleteDevice.as_view(),
                           name='deletedevice'
                       ),
                       url(
                           regex=r'device/admin/$',
                           view=login_required(views.AdminView.as_view()),
                           name='deviceadmin'
                       ),
                       url(
                           regex=r'vip/(?P<pk>\d+)/members',
                           view=views.MemberView.as_view(),
                           name='members'
                       ),
)

vips/models.py
from django.db import models

# Create your models here.
from django.db.models import Count
from vips.fetch import Netscaler


class Login(models.Model):
    user = models.CharField(max_length=16)
    password = models.CharField(max_length=16)

    def __unicode__(self):
        return '%s %s' % (self.user, self.password)


class Device(models.Model):
    ip = models.GenericIPAddressField()
    label = models.CharField(max_length=64)
    login = models.ForeignKey(Login)

    class Meta:
        ordering = ('label',)

    def __unicode__(self):
        return '%s' % self.label

class ServerManager(models.Manager):

    def server_poll(self, device=Device):
        """
        takes a query object of type Device, connects to that host, and then gets
        all the vip info

        then all the information is entered into the database
        :param device: query object
        :return:
        """

        remote = Netscaler(host=device.ip,
                           username=device.login.user,
                           password=device.login.password)

        for key, val in remote.get_servers().iteritems():
            Server.objects.update_or_create(name=val['Name'],
                                         address=val['IPAddress'],
                                         state=val['State'],
                                         device=device)


class Server(models.Model):
    name = models.CharField(max_length=64)
    state = models.CharField(max_length=16)
    address = models.GenericIPAddressField()
    device = models.ForeignKey(Device, related_name='servers')
    updated = models.DateTimeField(auto_now=True)

    objects = ServerManager()

    def __unicode__(self):
        return '%s' % self.name


class VipManager(models.Manager):

    def vips_poll(self, device=Device, debug=False):
        """
        connects to the netscaler gets all the vip data and enters it into the db
        :return:
        """
        remote = Netscaler(host=device.ip,
                           username=device.login.user,
                           password=device.login.password)

        for key, val in remote.get_vips(debug=debug).iteritems():
            Vip.objects.update_or_create(label=val['label'],
                                         address=val['address'],
                                         port=val['port'],
                                         state=val['state'],
                                         effective_state=val['effective state'],
                                         device=device)

    def graph(self):
        colors =["#f30000",
                 "#0600f3",
                 "#00b109",
                 "#14e4b4",
                 "#0fe7fb",
                 "#67f200",
                 "#ff7e00",
                 "#8fe4fa",
                 "#ff5300",
                 "#640000",
                 "#3854d1",
         ]
        result = Vip.objects.values('state').annotate(value=Count('state'))

        i = 1
        for each in result:
            try:
                each.update({'color': colors[i]})
            except IndexError:
                i = 1
            i += 1
            if i > len(colors):
                i = 1

        return result

    def vips_per_device_graph(self):
        colors =["#f30000",
                 "#0600f3",
                 "#00b109",
                 "#14e4b4",
                 "#0fe7fb",
                 "#67f200",
                 "#ff7e00",
                 "#8fe4fa",
                 "#ff5300",
                 "#640000",
                 "#3854d1",
         ]

        result = Vip.objects.values('device__label').annotate(value=Count('label'))

        #todo there must be a better way to do this....
        i = 1
        for each in result:
            try:
                each.update({'color': colors[i]})
            except IndexError:
                i = 1
            i += 1
            if i > len(colors):
                i = 1

        return result

class Vip(models.Model):
    label = models.CharField(max_length=32)
    address = models.GenericIPAddressField()
    port = models.IntegerField()
    state = models.CharField(max_length=16)
    effective_state = models.CharField(max_length=16)
    device = models.ForeignKey(Device, related_name='vips', default=None, null=True)
    updated = models.DateTimeField(auto_now=True)

    objects = VipManager()

    def __unicode__(self):
        return '%s' % self.label


class MemberManager(models.Manager):

    def members_poll(self, vip=Vip, debug=False):
        """

        :param device:
        :return:
        """
        remote = Netscaler(host=vip.device.ip,
                           username=vip.device.login.user,
                           password=vip.device.login.password)

        for key, val in remote.get_members(vip.label).iteritems():
            if debug == True:
                print key, val
            if val != 'empty':
                Member.objects.update_or_create(label=val['label'],
                                                address=val['address'],
                                                port=val['port'],
                                                protocol=val['protocol'],
                                                state=val['state'],
                                                vip=vip)


class Member(models.Model):
    label = models.CharField(max_length=32)
    address = models.GenericIPAddressField()
    port = models.IntegerField()
    protocol = models.CharField(max_length=16)
    state = models.CharField(max_length=16)
    vip = models.ForeignKey(Vip, related_name='members')
    update = models.DateTimeField(auto_now=True)

    objects = MemberManager()

    def __unicode__(self):
        return '%s' % self.label

vips/forms.py
__author__ = 'dambl_000'

from django.forms import ModelForm, Form
from django import forms
from vips.models import Device

class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = ['label', 'ip', 'login']

vips/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, CreateView, DeleteView
from vips.forms import DeviceForm
from vips.models import Device, Vip, Member

class LoginRequiredMixin(object):

    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

class IndexView(ListView):
    template_name = 'vips/index.html'
    model = Device
    context_object_name = 'devices'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['stategraph'] = Vip.objects.graph()
        context['devicegraph'] =  Vip.objects.vips_per_device_graph()
        return context


class AdminView(ListView):
    template_name = 'vips/deviceadmin.html'
    model = Device
    context_object_name = 'devices'

    def get_context_data(self, **kwargs):
        context = super(AdminView, self).get_context_data(**kwargs)
        context['deviceform'] = DeviceForm()
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AdminView, self).dispatch(*args, **kwargs)


class DeviceList(ListView):
    template_name = 'vips/device_list.html'
    context_object_name = 'devices'
    model = Device


class CreateDevice(CreateView):
    model = Device
    form_class = DeviceForm
    template_name = 'vips/device_form.html'
    success_url = reverse_lazy('vips:deviceadmin')


class DeleteDevice(DeleteView):
    model = Device
    template_name = 'vips/deleteform.html'
    success_url = reverse_lazy('vips:deviceadmin')


class MemberView(ListView):
    template_name = 'vips/memberlist.html'
    model = Member
    context_object_name = 'members'

    def get_queryset(self):
        return self.model.objects.filter(vip__id=self.kwargs['pk'])

vips/templates/vips/deleteform.html
<form class="form-inline" action="{% url 'vips:deletedevice' object.id %}" id="deletedeviceform" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-default btn-sm" type="submit" value="Confirm" />
</form>

vips/templates/vips/device_form.html
{% load staticfiles %}

<form class="form form-inline" id="post-form" action="{% url 'vips:createdevice'%}" method="post">
<legend>Create Device</legend>
    {% csrf_token %}
    {%  for field in deviceform %}
        {% if field.errors %}
            {% for error in  field.errors %}
                {{ error }}
            {% endfor %}
        {% else %}
             <div class="form-group">
                    <label class="control-label">{{ field.label }}</label>
                    {{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
        {% endif %}
    {% endfor %}
    <input class="btn btn-default btn-sm" type="submit" value="Submit" />
</form>

vips/templates/vips/device_list.html
<table id="devicetable" class="table table-condensed table-hover table-bordered">
    <thead>
    <tr class="text-left">
        <th>Name</th>
        <th>Address</th>
        <th>
            <a href="#modal-device" class="btn btn-default btn-sm" data-toggle="modal" >
                <span class="glyphicon glyphicon-plus-sign"></span>
            </a>
        </th>
    </tr>
    </thead>
    <tbody>
    {% if devices %}
        {% for device in devices %}
            <tr>
            <td>{{ device.label }}</td>
            <td>{{ device.ip }}</td>
            <td>
                <script>
                    var url{{ device.id }} = "{% url 'vips:deletedevice' device.id %}";
                    var tempmodal = $('#modal-delete');
                    var temptable = $('#devicetable');
                </script>
                <button type="button" class="btn btn-default btn-sm"
                   onclick='fillmodal("#device-delete", "{% url 'vips:deletedevice' device.id %}", "#modal-delete");'>
                    <span class="glyphicon glyphicon-remove"></span>
                </button>

            </td>
            </tr>
        {% endfor %}
        {% else %}
            <tr>
            <td><p>there is nothing in the database</p></td>
            <td></td>
            <td></td>
            </tr>
    {% endif %}
    </tbody>
    {% if error %}
        <tr><td>{{ error }}</td></tr>
    {% endif %}
</table>

vips/templates/vips/deviceadmin.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<script>
$(document).ready(function(){
    var temp = $('.modal').on('show.bs.modal', function(){
            console.log('modal is shown');
            console.log(this.id);
            //for some reason this return an array???
            return $(this)[0];
        });

    // Submit post on submit
    $('#post-form').live('submit', function(event) {
        console.log(event);
        event.preventDefault();
        console.log('Clicked on Submit');

        create_post($(this), temp, $('#content'));
        return false;
    });

    $(".modal").on('hide.bs.modal', function(){
        console.log('Modal was hidden from the user');
    });
});
</script>
        <div id='content' class="col-lg-12 main">
            {%  include 'vips/device_list.html'%}
        </div>
{% endblock %}


{% block modal %}
<!-- Modal HTML -->
    <div id="modal-device" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body" id="device-form">

                {% if deviceform %}
                    {% include 'vips/device_form.html' %}
                {% endif %}
                </div>
            </div>
        </div>

    </div>
    <div id="modal-delete" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body" id="device-delete">
                    <!-- place holder -->
                </div>
            </div>
        </div>

    </div>
{% endblock %}

vips/templates/vips/index.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<script src="{%  static 'js/d3.min.js' %}"></script>
<script src="{% static 'js/d3pie.min.js' %}"></script>

{% if devices %}
<div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-pills nav-stacked col-lg-2 main">
        <li class="active"><a href="#tab1" data-toggle="tab">Summary</a></li>
        {% for device in devices %}
            <li id="device{{ device.id }}"><a href="#tab{{ device.id }}" data-toggle="tab">{{ device.label }}</a></li>
        {% endfor %}
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <div class="row">
                <div class="col-lg-4 pull-left" id='pieChart'></div>
                <div class="col-lg-4" id="deviceChart"></div>
            </div>
            <script>
                var pie = new d3pie("pieChart", {
                    "header": {
                        "title": {
                            "text": "Vips",
                            "fontSize": 24,
                            "font": "open sans"
                        },
                        "subtitle": {
                            "color": "#999999",
                            "fontSize": 12,
                            "font": "open sans"
                        },
                        "titleSubtitlePadding": 9
                    },
                    "footer": {
                        "color": "#999999",
                        "fontSize": 10,
                        "font": "open sans",
                        "location": "bottom-left"
                    },
                    "size": {
                        "canvasWidth": 610,
                        "pieOuterRadius": "90%"
                    },
                    "data": {
                        "sortOrder": "value-desc",
                        "content": [
                            {% for item in stategraph %}
                            {
                                "label": "{{ item.state }}",
                                "value": {{ item.value }},
                                "color": "{{ item.color }}"
                            },
                            {% endfor %}

                        ]
                    },
                    "labels": {
                        "outer": {
                            "pieDistance": 32
                        },
                        "inner": {
                            "hideWhenLessThanPercentage": 3
                        },
                        "mainLabel": {
                            "fontSize": 11
                        },
                        "percentage": {
                            "color": "#ffffff",
                            "decimalPlaces": 0
                        },
                        "value": {
                            "color": "#adadad",
                            "fontSize": 11
                        },
                        "lines": {
                            "enabled": true
                        },
                        "truncation": {
                            "enabled": true
                        }
                    },
                    "effects": {
                        "pullOutSegmentOnClick": {
                            "speed": 400,
                            "size": 8
                        }
                    },
                    "misc": {
                        "gradient": {
                            "enabled": true,
                            "percentage": 100
                        }
                    }
                });

            var pie2 = new d3pie("deviceChart", {
                    "header": {
                        "title": {
                            "text": "Vips per Device",
                            "fontSize": 32,
                            "font": "open sans"
                        },
                        "subtitle": {
                            "color": "#999999",
                            "fontSize": 12,
                            "font": "open sans"
                        },
                        "titleSubtitlePadding": 9
                    },
                    "footer": {
                        "color": "#999999",
                        "fontSize": 10,
                        "font": "open sans",
                        "location": "bottom-left"
                    },
                    "size": {
                        "canvasWidth": 620,
                        "pieOuterRadius": "90%"
                    },
                    "data": {
                        "sortOrder": "value-desc",
                        "content": [
                            {% for item in devicegraph %}
                            {
                                "label": "{{ item.device__label }}",
                                "value": {{ item.value }},
                                "color": "{{ item.color }}"
                            },
                            {% endfor %}

                        ]
                    },
                    "labels": {
                        "outer": {
                            "pieDistance": 24
                        },
                        "inner": {
                            "hideWhenLessThanPercentage": 3
                        },
                        "mainLabel": {
                            "fontSize": 11
                        },
                        "percentage": {
                            "color": "#ffffff",
                            "decimalPlaces": 0
                        },
                        "value": {
                            "color": "#adadad",
                            "fontSize": 11
                        },
                        "lines": {
                            "enabled": true
                        },
                        "truncation": {
                            "enabled": true
                        }
                    },
                    "effects": {
                        "pullOutSegmentOnClick": {
                            "speed": 400,
                            "size": 8
                        }
                    },
                    "misc": {
                        "gradient": {
                            "enabled": true,
                            "percentage": 100
                        }
                    }
                });
            </script>
        </div>

        {% for device in devices %}
            <div class="tab-pane" id="tab{{ device.id }}">
                <div class="row main">
                    <div class="col-lg-5">
                        <table class="table table-bordered table-condensed">
                            <thead>
                            <tr>
                                <th colspan="5" class="text-center">Total Vips: {{ device.vips.count }}</th>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Port</th>
                                <th>State</th>
                                <th>Effective State</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for vip in device.vips.all %}
                                <tr>
                                    <td><a style="cursor: pointer;" onclick="getPajax('{% url "vips:members" vip.id %}', '#memberdiv{{ device.id }}');"> {{ vip.label }}</a></td>
                                    <td>{{ vip.address }}</td>
                                    <td>{{ vip.port }}</td>
                                    {% if vip.state == "UP" %}
                                        <td><span class='label label-success'>{{ vip.state }}</span></td>
                                     {% elif vip.state == "DOWN" %}
                                        <td><span class='label label-danger'>{{ vip.state }}</span></td>
                                    {% else %}
                                        <td><span class="label label-default">{{ vip.state }}</span></td>
                                    {% endif %}
                                    {% if vip.effective_state == "UP"%}
                                        <td><span class="label label-success">{{ vip.effective_state }}</span></td>
                                    {% elif vip.effective_state == "DOWN" %}
                                        <td><span class="label label-danger">{{ vip.effective_state }}</span></td>
                                    {% else %}
                                        <td><span class="label label-default">{{ vip.effective_state }}</span></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div id='memberdiv{{ device.id }}' class="col-lg-5 col-lg-offset-7 fixed">
                        <!-- place holder for table -->
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <div>
    <p>there is nothing in the database</p>
    </div>
{% endif %}

{% endblock %}

vips/templates/vips/memberlist.html
<table class="tabl table-bordered table-condensed">
    <thead>
        <tr>
            <th colspan="5">{{ members.first.vip.label }}</th>
        </tr>
        <tr>
            <th>Member</th>
            <th>Address</th>
            <th>Protocol</th>
            <th>Port</th>
            <th>State</th>
        </tr>
    </thead>
    <tbody>
        {% if members %}
        {% for member in members %}
            <tr>
                <td>{{ member.label }}</td>
                <td>{{ member.address }}</td>
                <td>{{ member.protocol }}</td>
                <td>{{ member.port }}</td>
                {% if member.state == 'DOWN' %}
                    <td><span class='label label-danger'>{{ member.state }}</span></td>
                {% elif member.state == 'UP' %}
                    <td><span class='label label-success'>{{ member.state }}</span></td>
                {% else %}
                    <td><span class='label label-default'>{{ member.state }}</span></td>
                {% endif %}
            </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="5"><h3>There are no members in this Vip</h3></td>
        </tr>
        {% endif %}
    </tbody>
</table>