netscaler/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^', include('vips.urls', namespace='vips' )),
)

vips/urls.py
from django.contrib.auth.decorators import login_required

__author__ = 'jeffrey.dambly'

from django.conf.urls import patterns, url
from vips import views

urlpatterns = patterns('',
                       url(
                           regex=r'^$',
                           view=views.IndexView.as_view(),
                           name='index'
                       ),
                       url(
                           regex=r'^devices/$',
                           view=views.DeviceList.as_view(),
                           name='devices'
                       ),
                       url(
                           regex=r'^device/create/$',
                           view=views.CreateDevice.as_view(),
                           name='createdevice'
                       ),
                       url(
                           regex=r'device/(?P<pk>\d+)>/delete',
                           view=views.DeleteDevice.as_view(),
                           name='deletedevice'
                       ),
                       url(
                           regex=r'device/admin/$',
                           view=login_required(views.AdminView.as_view()),
                           name='deviceadmin'
                       ),
                       url(
                           regex=r'vip/(?P<pk>\d+)/members',
                           view=views.MemberView.as_view(),
                           name='members'
                       ),
)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
      {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="dashboard">
    <meta name="author" content="Jeff d'Ambly">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Network Tools{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fixbootstrap.css' %}" rel="stylesheet">

    <script type='text/javascript' src="{%  static 'js/jquery-1.11.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'vips:index' %}">Netscaler</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'vips:deviceadmin' %}">Admin</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>
    <div class="row">
        {% block content %}

        {% endblock content %}
    </div>

    {% block modal %}
    {% endblock %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type='text/javascript' src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  </body>
</html>

templates/modal.html
<!-- Modal HTML -->
    <div id="{% block id %}modalform{% endblock %}" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body" id="modal-form">
                <!-- placeholder for whatever-->
                </div>
            </div>
        </div>
    </div>